PKIClassroom: Servlet.homePage Class Reference
Servlet.homePage Class Reference
Public Member Functions
homePage ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Detailed Description
Servlet implementation class change
Constructor & Destructor Documentation
homePage()
Servlet.homePage.homePage ()
See also
HttpServlet::HttpServlet()
Member Function Documentation
doGet()
void Servlet.homePage.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
See also
HttpServlet::doGet(HttpServletRequest request, HttpServletResponse response)
References parser.Aggregator.findCourse(), util.Utils.findCoursesSwap(), util.Utils.findRoomSameTime(), util.Utils.getAggregator(), parser.Course.getCourseMeeting(), parser.Course.getEnrollment(), parser.Course.getMaxEnrollment(), parser.Course.getRoom(), and parser.Room.getRoomNumber().
doPost()
void Servlet.homePage.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
See also
HttpServlet::doPost(HttpServletRequest request, HttpServletResponse response)
The documentation for this class was generated from the following file:
src/main/java/Servlet/homePage.java