PKIClassroom: util.Utils Class Reference
util.Utils Class Reference
Public Member Functions
Utils (Aggregator A)
Aggregator getAggregator ()
String[] findRoomSameTime (Course c, int maxEnrollement)
Room[] findRoomsLargerThanMaxEnrollment (Course cc, int maxEnrollment)
ArrayList< Course > findCoursesSwap (Course c, int enrollment)
String timeSwap (Course a, Course b)
String reassignRoomSameTime (Course courseTitle, String newRoomNum)
Constructor & Destructor Documentation
Utils()
util.Utils.Utils (Aggregator A)
References parser.Aggregator.getCourses(), and parser.Aggregator.getRooms().
Member Function Documentation
findCoursesSwap()
ArrayList< Course > util.Utils.findCoursesSwap (Course c, int enrollment)
References parser.Course.getEnrollment(), parser.Course.getMaxEnrollment(), parser.Course.getMeetingDuration(), and parser.Course.getMeetingPattern().
findRoomSameTime()
String[] util.Utils.findRoomSameTime (Course c, int maxEnrollement)
References util.Utils.findRoomSameTime(), util.Utils.findRoomsLargerThanMaxEnrollment(), parser.Room.getCapacity(), parser.Course.getCourseMeeting(), and parser.Room.getRoomNumber().
findRoomsLargerThanMaxEnrollment()
Room[] util.Utils.findRoomsLargerThanMaxEnrollment (Course cc, int maxEnrollment)
References parser.Course.getMeetingDuration(), and parser.Course.getMeetingPattern().
getAggregator()
Aggregator util.Utils.getAggregator ()
reassignRoomSameTime()
String util.Utils.reassignRoomSameTime (Course courseTitle, String newRoomNum)
References parser.Aggregator.findRoomByNum(), parser.Course.getCourseMeeting(), parser.Course.getCourseSection(), parser.Course.getRoom(), parser.Room.getRoomNumber(), parser.Course.release(), parser.Course.schedule(), parser.Course.setCourseMeeting(), and parser.Course.setRoom().
timeSwap()
String util.Utils.timeSwap (Course a, Course b)
References parser.Course.getCourseMeeting(), parser.Course.getCourseSection(), parser.Course.getMeetingDuration(), parser.Course.getRoom(), parser.Room.getRoomNumber(), parser.Course.release(), parser.Course.schedule(), parser.Course.setCourseMeeting(), and parser.Course.setRoom().
The documentation for this class was generated from the following file:
src/main/java/util/Utils.java