PKIClassroom: parser.TimeTable Class Reference
parser.TimeTable Class Reference
Public Member Functions
TimeTable ()
Course getCourseAt (int d, int t)
boolean checkAvailable (int d, int t, int du)
void set (Course c) throws ScheduleException
void release (Course c) throws ScheduleException
void restoreRelease (Course c) throws ScheduleException
void restore (Course c) throws ScheduleException
Constructor & Destructor Documentation
TimeTable()
parser.TimeTable.TimeTable ()
References parser.Constants.NUM_DAYS, and parser.Constants.NUM_FIFTEENS.
Member Function Documentation
checkAvailable()
boolean parser.TimeTable.checkAvailable (int d, int t, int du)
Referenced by parser.TimeTable.set().
getCourseAt()
Course parser.TimeTable.getCourseAt (int d, int t)
release()
void parser.TimeTable.release (Course c) throws ScheduleException
Referenced by parser.Course.releaseOriginal().
restore()
void parser.TimeTable.restore (Course c) throws ScheduleException
restoreRelease()
void parser.TimeTable.restoreRelease (Course c) throws ScheduleException
Referenced by parser.Course.release().
set()
void parser.TimeTable.set (Course c) throws ScheduleException
References parser.TimeTable.checkAvailable().
Referenced by parser.Course.schedule().
The documentation for this class was generated from the following file:
src/main/java/parser/TimeTable.java