PKIClassroom: parser.Aggregator Class Reference
parser.Aggregator Class Reference
Public Member Functions
Aggregator (String[] paths)
Course[] getCourses ()
String[] getCourseNames ()
Room[] getRooms ()
boolean finalOutput ()
Course findCourse (String name)
Room findRoomByNum (String name)
String toString ()
Detailed Description
The master controller class, that handles taking in multiple CSVs, turning each into its own Document. Creates a master list of Rooms, finds all Courses, filters Courses to relevant ones, schedules those Courses, and creates an easy access list. Also contains lookup methods for Courses and Rooms.
Author
jwillson
Constructor & Destructor Documentation
Aggregator()
parser.Aggregator.Aggregator (String[] paths)
Constructor of aggregator, uses an array of file paths as Strings
Parameters
paths - an array of file paths
Member Function Documentation
finalOutput()
boolean parser.Aggregator.finalOutput ()
Aggregator level call to output all file changes, application should be closed after execution
Returns
true if output is successful
References parser.Document.output().
findCourse()
Course parser.Aggregator.findCourse (String name)
Lookup by String to find the associated relevant Course
Parameters
name - the name of the Course being looked for in XXXX YYYY-ZZZ format
Returns
the associated relevant Course object
findRoomByNum()
Room parser.Aggregator.findRoomByNum (String name)
Lookup by String to find the associated valid Room
Parameters
name - the number of the room
Returns
the associated Room object
References parser.Room.getRoomNumber().
getCourseNames()
String[] parser.Aggregator.getCourseNames ()
Accessor for the array of all Course names
Returns
all relevant Course names
getCourses()
Course[] parser.Aggregator.getCourses ()
Accessor for the array of relevant Courses
Returns
all relevant Courses
getRooms()
Room[] parser.Aggregator.getRooms ()
Accessor for the array of all valid Rooms
Returns
all valid Rooms
toString()
String parser.Aggregator.toString ()
Standard output format for debugging
References parser.Aggregator.toString().
The documentation for this class was generated from the following file:
src/main/java/parser/Aggregator.java