PKIClassroom: Servlet.changesPage Class Reference
Servlet.changesPage Class Reference
Public Member Functions
changesPage ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Detailed Description
Servlet implementation class change
Constructor & Destructor Documentation
changesPage()
Servlet.changesPage.changesPage ()
See also
HttpServlet::HttpServlet()
Member Function Documentation
doGet()
void Servlet.changesPage.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
See also
HttpServlet::doGet(HttpServletRequest request, HttpServletResponse response)
References parser.Aggregator.findCourse(), util.Utils.getAggregator(), util.Utils.reassignRoomSameTime(), and util.Utils.timeSwap().
doPost()
void Servlet.changesPage.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
See also
HttpServlet::doPost(HttpServletRequest request, HttpServletResponse response)
The documentation for this class was generated from the following file:
src/main/java/Servlet/changesPage.java