PKIClassroom: parser.Course Class Reference
parser.Course Class Reference
Public Member Functions
Course ()
Course (String line, Room[] rooms)
void setCourseMeeting (String patt)
void setRoom (Room r)
void setMaxEnrollment (String m)
String getCourseSection ()
int getMeetingPattern ()
int getMeetingTime ()
int getMeetingDuration ()
String getCourseMeeting ()
Room getRoom ()
int getEnrollment ()
int getMaxEnrollment ()
void schedule () throws ScheduleException
void release () throws ScheduleException
void revert ()
String toString ()
Public Member Functions inherited from parser.Line
Line ()
Line (String input)
String toString ()
Protected Member Functions
String getBuilding ()
int[] getDays ()
int getPC ()
String[] getPCField ()
void setPC (int a, Course b)
String output ()
Protected Member Functions inherited from parser.Line
void parseOriginalDayTime ()
int[] getOriginalDays ()
String output ()
String outputOriginal ()
Protected Attributes
int day
int time
int duration
boolean changed
Protected Attributes inherited from parser.Line
int oday
int otime
int oduration
String[] line
Detailed Description
Course is a subclass of Line. It utilizes Line's immutable nature to always keep a clean revert state, but allows editting and more complex usage and parsing for Line's that are actually Courses and not just headers/fillers in the CSV.
Author
jwillson
Constructor & Destructor Documentation
Course() [1/2]
parser.Course.Course ()
Default constructor, only used for fully null Blocker in TimeTable
Course() [2/2]
parser.Course.Course (String line, Room[] rooms)
Initializes the immutable Line, creates a local copy of the pieces, and then parses it apart into the relevant information for modifying.
Parameters
line - a row from Document as a String
rooms - an array of all valid Rooms
References parser.Constants.COL_COUNT, parser.Constants.CROSSLISTINGS, parser.Line.line, parser.Line.parseOriginalDayTime(), and parser.Course.revert().
Member Function Documentation
getBuilding()
String parser.Course.getBuilding () protected
Accessor for the Building that this Course is scheduled in
Returns
what building this Courses room is in
References parser.Line.line, and parser.Constants.ROOM.
getCourseMeeting()
String parser.Course.getCourseMeeting ()
Accessor for the Meeting Pattern full String
Returns
the contents of the column in the CSV representing the meeting pattern
References parser.Constants.MEET_PATT.
getCourseSection()
String parser.Course.getCourseSection ()
Accessor for the Course Section listing to be displayed on front end and compared for equality
Returns
the Course and Section number of this Course
References parser.Constants.COURSE, parser.Line.line, and parser.Constants.SEC_NUM.
getDays()
int[] parser.Course.getDays () protected
Converts the day pattern into an array of days
Returns
an array containing the numeric value of days this course is on
References parser.Course.day, parser.Constants.M, parser.Constants.T, parser.Constants.Th, and parser.Constants.W.
getEnrollment()
int parser.Course.getEnrollment ()
Accessor for the current enrollment of this Course
Returns
the current enrollment
References parser.Constants.ENROLLMENT.
getMaxEnrollment()
int parser.Course.getMaxEnrollment ()
Accessor for the max enrollment of this Course
Returns
the current max enrollment
References parser.Constants.MAX_ENROLL.
getMeetingDuration()
int parser.Course.getMeetingDuration ()
Accessor for the duration of this Course
Returns
the duration of this course in 96 segment day time
References parser.Course.duration.
getMeetingPattern()
int parser.Course.getMeetingPattern ()
Accessor for the day pattern that this Course is scheduled on
Returns
a pattern, can be split into an array of days by a helper
References parser.Course.day.
getMeetingTime()
int parser.Course.getMeetingTime ()
Accessor for the time that this Course is scheduled at
Returns
the start time of this course in 96 segment day time
References parser.Course.time.
getPC()
int parser.Course.getPC () protected
getPCField()
String[] parser.Course.getPCField () protected
References parser.Constants.CROSSLISTINGS.
getRoom()
Room parser.Course.getRoom ()
Accessor for the Room this Course is currently in
Returns
the Room the course is in
References parser.Course.getRoom().
output()
String parser.Course.output () protected
Converts the String array of a row back into CSV format as a single String
Returns
a csv formatted row
Reimplemented from parser.Line.
release()
void parser.Course.release () throws ScheduleException
Releases the currently assigned schedule slot for this course
Exceptions
ScheduleException - when this course is not currently scheduled, it cannot be descheduled
References parser.Course.release(), and parser.TimeTable.release().
revert()
void parser.Course.revert ()
Reverts all values of this Course to their default values form the CSV using the Line parent
References parser.Course.changed, parser.Line.line, and parser.Course.revert().
schedule()
void parser.Course.schedule () throws ScheduleException
Schedules this Course in its assigned Room based on its meeting pattern
Exceptions
ScheduleException - when this course does not have a room, it cannot be scheduled
References parser.TimeTable.set().
setCourseMeeting()
void parser.Course.setCourseMeeting (String patt)
Sets the meeting pattern for this course
Parameters
patt - a new meeting pattern in String form
References parser.Course.changed, parser.Constants.MEET_PATT, and parser.Course.setCourseMeeting().
setMaxEnrollment()
void parser.Course.setMaxEnrollment (String m)
Sets the max enrollment for this course
Parameters
m - a String that is a number that is the max enrollment
References parser.Course.changed, parser.Constants.MAX_ENROLL, and parser.Course.setMaxEnrollment().
setPC()
void parser.Course.setPC (int a, Course b) protected
setRoom()
void parser.Course.setRoom (Room r)
Sets the room for this course
Parameters
r - a room object that this course is in
References parser.Course.changed, parser.Room.getBuilding(), parser.Room.getRoomNumber(), parser.Constants.ROOM, and parser.Course.setRoom().
toString()
String parser.Course.toString ()
Standard output format for debugging
Reimplemented from parser.Line.
Member Data Documentation
changed
boolean parser.Course.changed protected
Flag boolean for when Course diverges from Line. Can be used to find the pieces for a changelog.
day
int parser.Course.day protected
The courses current day pattern, time, and duration
duration
int parser.Course.duration protected
time
int parser.Course.time protected
The documentation for this class was generated from the following file:
src/main/java/parser/Course.java